// Lattices, their point groups, and connected site clusters.
//
// Sites are integer pairs (a, b) at a*e1 + b*e2.  The chain uses e1 alone
// (b = 0), the square lattice e1 = (1, 0), e2 = (0, 1), and the triangular
// lattice e1 = (1, 0), e2 = (1/2, sqrt3/2).  The honeycomb and kagome
// lattices are triangular lattices without their hexagon centres, the
// points a - b = 0 (mod 3) and the points with a and b both even, so they
// have two and three sites per unit cell.  A site cluster is a connected
// set of sites carrying every lattice bond between its members; clusters are
// classified modulo translation and the point group.
#pragma once

#include <compare>
#include <optional>
#include <string>
#include <utility>
#include <vector>

namespace nlce {

struct Site {
  int a = 0;
  int b = 0;
  auto operator<=>(const Site&) const = default;
};

inline Site operator+(Site s, Site t) { return {s.a + t.a, s.b + t.b}; }
inline Site operator-(Site s, Site t) { return {s.a - t.a, s.b - t.b}; }

// Integer 2x2 matrix acting on (a, b).
struct PointOp {
  int m0, m1, m2, m3;
  Site operator()(Site s) const { return {m0 * s.a + m1 * s.b, m2 * s.a + m3 * s.b}; }
  bool operator==(const PointOp&) const = default;
};

struct Lattice {
  std::string name;            // "chain", "square", "triangular" or "honeycomb"
  std::vector<Site> dirs;      // positive bond directions, between two sites
  std::vector<PointOp> group;  // point group about the origin, identity first
  // Translations: the lattice generated by (cell.p, 0) and (cell.q, cell.r),
  // in Hermite normal form (0 <= q < p).  residue() numbers the p * r cosets
  // of the translations; anchors[residue] is the site of that coset to which
  // a cluster's smallest site is translated, or empty where the coset holds
  // no sites.  Bravais lattices have p = r = 1.
  struct Cell {
    int p = 1, q = 0, r = 1;
  } cell;
  std::vector<std::optional<Site>> anchors{Site{}};
  bool currents = false;  // three-sublattice staggered current (chi, m0) defined

  int residue(Site s) const;
  bool is_site(Site s) const { return anchors[residue(s)].has_value(); }
  int cell_sites() const;
};

const Lattice& chain_lattice();
const Lattice& square_lattice();
const Lattice& triangular_lattice();
const Lattice& honeycomb_lattice();
const Lattice& kagome_lattice();

// Throws std::invalid_argument for an unknown name.
const Lattice& lattice_by_name(const std::string& name);

// Lexicographically smallest point-group image of a displacement.
Site canonical_displacement(const Lattice& lat, Site d);
int displacement_orbit_size(const Lattice& lat, Site d);

// Three-sublattice label l = (2a + b) mod 3 of the triangular lattice and the
// staggered current sign of the oriented bond p -> q: +1 if
// l(q) = l(p) + 1 (mod 3), else -1.
int sublattice(Site s);
int current_sign(Site p, Site q);

using Bond = std::pair<Site, Site>;

// Every lattice bond with both endpoints in `sites`, each as (smaller,
// larger) and the list sorted.
std::vector<Bond> induced_bonds(const Lattice& lat, const std::vector<Site>& sites);

// Canonical representative: translated so its smallest site is the anchor of
// its residue, minimised over the point group, sorted.
std::vector<Site> canonical_sites(const Lattice& lat, const std::vector<Site>& sites);

// Number of distinct translation classes in the point-group orbit.
int site_orbit_size(const Lattice& lat, const std::vector<Site>& sites);

// reps[s] lists the canonical connected clusters of s sites, s = 1..smax.
// Size 1 holds one site of each sublattice inequivalent under the point
// group; each larger size is grown from the previous one by adding a
// neighbouring site.  The order of discovery is deterministic.
std::vector<std::vector<std::vector<Site>>> enumerate_site_clusters(const Lattice& lat, int smax);

}  // namespace nlce
